Repository portto/wallet-web-ui, pull requests merged in 2023-01, with the labels that each got.

#6 Feature/update header
  .env.example
  .eslintrc.json
  src/components/Header/index.tsx
  src/components/Loading.tsx
  src/images/icons/logo.svg
  src/translations/en.json
  src/translations/ja.json
  src/translations/ko.json
  src/translations/localeNames.json
  src/translations/ru.json
  src/translations/zh-Hans.json
  src/translations/zh-Hant.json
Labels: Feature

#7 [Feat] Add DappLogo component.
  package.json
  src/assets/images/icons/arrow-back.svg
  src/assets/images/icons/arrow-next.svg
  src/assets/images/icons/close.svg
  src/assets/images/icons/ic-dapp-placeholder.png
  src/assets/images/icons/logo.svg
  src/assets/lottie/logo-loading-left.json
  src/assets/lottie/logo-loading-right.json
  src/components/DappLogo/index.tsx
  src/components/Field/index.tsx
  src/components/Header/index.tsx
  src/components/Loading.tsx
  yarn.lock
Labels: Feature

#8 [Enhance] Throw the error caught from the request
  src/apis/proxies/backend.ts
  src/apis/wallet.ts
  src/features/Authenticate/components/Input2FA.tsx
  src/features/Authenticate/components/InputEmail.tsx
  src/features/EVM/Signing/components/Connecting.tsx
  src/features/EVM/Signing/components/NonCustodial.tsx
  src/features/EVM/Transaction/components/Connecting.tsx
  src/features/EVM/Transaction/components/NonCustodial.tsx
  src/services/Sentry/index.ts
Labels: Feature

#12 [Fix] Add the missing config for avoiding the build error
  src/mocks/config.ts
Labels: HotFix

#11 [Enhance] Prevent to click when the button it loading and update style
  src/components/Button.tsx
  src/theme.ts
Labels: Feature

#15 [Fix] Remove API mocks for now
  .gitignore
  src/index.tsx
  src/mocks/config.example.ts
  src/mocks/config.ts
  src/mocks/index.ts
Labels: BugFix

#17 Feature/authn UI
  .eslintrc.json
  public/index.html
  src/App.tsx
  src/apis/proxies/backend.ts
  src/assets/images/icons/check.svg
  src/assets/images/icons/error.svg
  src/assets/images/icons/input-loading.svg
  src/assets/images/icons/switch.svg
  src/components/Field/index.tsx
  src/components/Header/index.tsx
  src/components/Layout.tsx
  src/components/Loading.tsx
  src/components/LoadingLogo.tsx
  src/features/Authenticate/components/AccountConfirm.tsx
  src/features/Authenticate/components/Connecting.tsx
  src/features/Authenticate/components/EnableBlockchain.tsx
  src/features/Authenticate/components/Input2FA.tsx
  src/features/Authenticate/components/InputEmail.tsx
  src/features/Authenticate/components/InputOTP.tsx
  src/features/Authenticate/components/Queueing.tsx
  src/features/Authenticate/index.tsx
  src/features/EVM/Signing/index.tsx
  src/features/EVM/Transaction/index.tsx
  src/machines/authenticate/definition.ts
  src/machines/authenticate/services.ts
  src/services/Frame/eventHandlers.ts
  src/theme.ts
  src/translations/en.json
  src/translations/ja.json
  src/translations/ko.json
  src/translations/localeNames.json
  src/translations/ru.json
  src/translations/zh-Hans.json
  src/translations/zh-Hant.json
  src/types.ts
  src/utils/checkBlockchainEnabled.ts
  src/utils/checkEmailFormat.ts
  src/utils/fetchDappInfo.ts
  src/utils/formatAddress.ts
  src/utils/getBlockchainIcon.ts
  src/utils/getBlockchainStatus.ts
  src/utils/loginAndAcquireToken.ts
  src/utils/mapAssetsToAddresses.ts
  yarn.lock
Labels: Feature

#13 Add UI for transaction on EVM
  src/assets/images/icons/check-alert.svg
  src/assets/images/icons/check-blue.svg
  src/assets/images/icons/check-verified.svg
  src/components/Field/index.tsx
  src/features/EVM/Transaction/components/Main.tsx
  src/features/EVM/Transaction/components/TransactionContent.tsx
  src/features/EVM/Transaction/components/TransactionInfo.tsx
  src/features/EVM/Transaction/components/messages.js
Labels: Feature

#21 Feature/evm sign UI
  src/components/Field/index.tsx
  src/features/EVM/Signing/components/Connecting.tsx
  src/features/EVM/Signing/components/Main.tsx
  src/features/EVM/Signing/components/NonCustodial.tsx
  src/features/EVM/Signing/index.tsx
Labels: Feature

#23 [Fix] Login for non-custodial users
  src/machines/authenticate/services.ts
Labels: HotFix

#16 [Hoftix] Authentication machine
  src/machines/authenticate/definition.ts
Labels: HotFix

#24 Add non-custodial ui for evm transaction.
  src/features/EVM/Transaction/components/NonCustodial.tsx
  src/features/EVM/Transaction/index.tsx
Labels: Feature

#22 Cost information for transaction view when transfering.
  package.json
  src/apis/proxies/backend.ts
  src/apis/wallet.ts
  src/components/TransactionContent.tsx
  src/components/TransactionInfo.tsx
  src/features/EVM/Transaction/components/Connecting.tsx
  src/features/EVM/Transaction/components/Main.tsx
  src/features/EVM/Transaction/components/TransactionInfo.tsx
  src/features/EVM/Transaction/components/messages.js
  src/features/EVM/Transaction/hooks/useTransactionDetail.tsx
  src/machines/authenticate/definition.ts
  src/machines/signing/definition.ts
  src/machines/transaction/definition.ts
  src/types.ts
  src/utils/measureTextWidth.ts
  yarn.lock
Labels: Feature

#20 [Enhance] Submit the 2fa code when user types 6 characters
  src/App.tsx
  src/assets/images/icons/error.svg
  src/components/Layout.tsx
  src/context/layout.tsx
  src/features/Authenticate/components/Input2FA.tsx
  src/features/Authenticate/components/InputEmail.tsx
  src/features/Authenticate/index.tsx
  src/features/EVM/Signing/index.tsx
  src/features/EVM/Transaction/index.tsx
  src/index.tsx
  src/translations/en.json
  src/translations/ja.json
  src/translations/ko.json
  src/translations/ru.json
  src/translations/zh-Hans.json
  src/translations/zh-Hant.json
  src/utils/checkEmailFormat.ts
Labels: Feature

#27 [Enhance] Update the UI on tablet to be the same as the one on the desktop
  src/components/Layout.tsx
Labels: Feature
