Repository portto/wallet-web-ui, pull requests merged in 2023-02, with the labels that each got.

#25 [Feat] Add transaction view for flow.
  package.json
  src/App.tsx
  src/apis/wallet.ts
  src/components/TransactionInfo.tsx
  src/features/EVM/Signing/components/Connecting.tsx
  src/features/EVM/Transaction/components/Main.tsx
  src/features/EVM/Transaction/components/messages.js
  src/features/EVM/Transaction/hooks/useTransactionDetail.tsx
  src/features/Flow/Transaction/components/Connecting.tsx
  src/features/Flow/Transaction/components/Main.tsx
  src/features/Flow/Transaction/hooks/useTransactionDetail.ts
  src/features/Flow/Transaction/index.tsx
  src/services/Env/index.ts
  src/services/Flow/getFlowScriptWithTemplate.ts
  src/services/Flow/index.ts
  src/services/Flow/recognizeTx.ts
  src/types.ts
  src/utils/hashMsg.tsx
  yarn.lock
Labels: Feature

#26 Refine the way of using i18n strings in the UI component.
  src/components/FormattedMessage.tsx
  src/components/Loading.tsx
  src/components/TransactionContent.tsx
  src/components/TransactionInfo.tsx
  src/features/Authenticate/components/AccountConfirm.tsx
  src/features/Authenticate/components/EnableBlockchain.tsx
  src/features/Authenticate/components/Input2FA.tsx
  src/features/Authenticate/components/InputEmail.tsx
  src/features/Authenticate/components/InputOTP.tsx
  src/features/Authenticate/components/Queueing.tsx
  src/features/EVM/Signing/components/Main.tsx
  src/features/EVM/Signing/components/NonCustodial.tsx
  src/features/EVM/Transaction/components/Main.tsx
  src/features/EVM/Transaction/components/NonCustodial.tsx
  src/features/EVM/Transaction/components/messages.js
  src/messages/defaultMessages.json
  src/messages/index.ts
  src/translations/en.json
  src/translations/ja.json
  src/translations/ko.json
  src/translations/ru.json
  src/translations/zh-Hans.json
  src/translations/zh-Hant.json
  src/utils/constants.ts
Labels: refactor

#28 Fix the layout logic in flow chain, and env logic error.
  src/features/Flow/Transaction/index.tsx
  src/services/Env/index.ts
  src/services/Flow/recognizeTx.ts
Labels: BugFix

#29 [Fix] Wrong env variable for REACT_APP_ENV
  src/services/Amplitude/log.ts
  src/services/Env/index.ts
  src/services/Frame/utils.ts
  src/services/Sentry/index.ts
  src/theme.ts
Labels: HotFix

#31 Feature/flow sign
  src/App.tsx
  src/apis/wallet.ts
  src/components/Layout.tsx
  src/features/Authenticate/components/AccountConfirm.tsx
  src/features/Authenticate/index.tsx
  src/features/Flow/Signing/components/Connecting.tsx
  src/features/Flow/Signing/components/Main.tsx
  src/features/Flow/Signing/index.tsx
  src/machines/authenticate/definition.ts
  src/machines/authenticate/services.ts
  src/machines/signing/definition.ts
  src/machines/signing/services.ts
  src/services/Frame/eventHandlers.ts
  src/services/LocalStorage/constants.ts
Labels: Feature

#39 [Hotfix] Fix wrong server url env setting
  .env.example
  Dockerfile
Labels: HotFix

#37 Feature/evm sign message
  src/App.tsx
  src/apis/proxies/backend.ts
  src/apis/wallet.ts
  src/features/Aptos/Signing/components/Connecting.tsx
  src/features/EVM/Signing/components/Connecting.tsx
  src/features/EVM/Signing/components/Main.tsx
  src/features/EVM/Signing/components/NonCustodial.tsx
  src/features/EVM/Signing/index.tsx
  src/features/Flow/Signing/components/Connecting.tsx
  src/features/Flow/Signing/components/Main.tsx
  src/types.ts
Labels: Feature

#43 Add malicious tx alert ui.
  src/features/Flow/Transaction/components/DangerousTxAlert.tsx
  src/features/Flow/Transaction/components/Main.tsx
  src/features/Flow/Transaction/index.tsx
  src/machines/transaction/definition.ts
  src/messages/defaultMessages.json
  src/types.ts
  src/utils/isMaliciousTx.ts
Labels: Feature

#44 [Feature] Forward to the page entering OTP code if there's prefilled email
  .eslintrc.json
  src/apis/wallet.ts
  src/features/Authenticate/components/Connecting.tsx
  src/features/Authenticate/components/InputEmail.tsx
  src/features/Authenticate/components/Queueing.tsx
  src/features/Authenticate/index.tsx
  src/machines/authenticate/definition.ts
Labels: Feature

#45 [Feature] Scripts for shared accounts and enabling assets
  package.json
  src/apis/proxies/backend.ts
  src/apis/wallet.ts
  src/features/Authenticate/components/AccountConfirm.tsx
  src/features/Authenticate/components/EnableBlockchain.tsx
  src/global.d.ts
  src/hooks/useNonCustodialTransaction.tsx
  src/services/Env/index.ts
  src/services/Flow/cosignerAuth.ts
  src/services/Flow/fcl.ts
  src/services/Flow/getDeviceAuth.ts
  src/services/Flow/getLatestBlock.ts
  src/services/Flow/getNonCustodialAuth.ts
  src/services/Flow/getUserAccount.ts
  src/services/Flow/index.ts
  src/services/Flow/payerAuth.ts
  src/services/Flow/script/checkCollectionEnabled.ts
  src/services/Flow/script/constants.ts
  src/services/Flow/script/enableCollection.ts
  src/services/Flow/script/getLockedAddress.ts
  src/services/Flow/script/index.ts
  src/services/Flow/signWithKey.ts
  src/types.ts
  yarn.lock
Labels: Feature

#48 feature/add-console-version
  src/index.tsx
Labels: Feature

#38 Update authorization detail before closing the frame.
  src/apis/wallet.ts
  src/components/TransactionInfo.tsx
  src/features/Aptos/Transaction/components/Connecting.tsx
  src/features/Aptos/Transaction/components/Main.tsx
  src/features/EVM/Transaction/components/Connecting.tsx
  src/features/EVM/Transaction/components/Main.tsx
  src/features/Flow/Transaction/components/Connecting.tsx
  src/features/Flow/Transaction/components/Main.tsx
  src/features/Solana/Transaction/components/Connecting.tsx
  src/features/Solana/Transaction/components/Main.tsx
  src/machines/transaction/definition.ts
  src/machines/transaction/services.ts
Labels: Feature

#49 Feature/update flow node
  src/services/Flow/fcl.ts
Labels: Feature

#41 [Refactor] Still need to get the url from the browser if the app id does not present
  src/features/Aptos/Signing/components/Connecting.tsx
  src/features/Aptos/Signing/index.tsx
  src/features/Aptos/Transaction/components/Connecting.tsx
  src/features/Aptos/Transaction/index.tsx
  src/features/Authenticate/components/Connecting.tsx
  src/features/EVM/Signing/components/Connecting.tsx
  src/features/EVM/Signing/index.tsx
  src/features/EVM/Transaction/components/Connecting.tsx
  src/features/EVM/Transaction/index.tsx
  src/features/Flow/Signing/components/Connecting.tsx
  src/features/Flow/Signing/index.tsx
  src/features/Flow/Transaction/components/Connecting.tsx
  src/features/Flow/Transaction/index.tsx
  src/features/Solana/Transaction/components/Connecting.tsx
  src/features/Solana/Transaction/index.tsx
Labels: refactor

#50 [Enhance] Remove machineStates.RUN_INIT_SCRIPTS
  src/features/Authenticate/components/AccountConfirm.tsx
  src/features/Authenticate/components/RunInitScripts.tsx
  src/features/Authenticate/index.tsx
  src/machines/authenticate/definition.ts
Labels: refactor

#40 Feature/account proof
  src/apis/wallet.ts
  src/features/Authenticate/components/Connecting.tsx
  src/features/Authenticate/index.tsx
  src/machines/authenticate/definition.ts
  src/machines/authenticate/services.ts
  src/services/Frame/eventHandlers.ts
  src/types.ts
Labels: Feature

#52 [Fix] Store authenticationId
  src/features/Authenticate/index.tsx
Labels: HotFix

#53 [Fix] Update the node endpoint...
  src/services/Flow/fcl.ts
Labels: HotFix

#55 [Feature] Press enter to submit email
  src/features/Authenticate/components/InputEmail.tsx
Labels: Feature

#42 [Feature] Pre Authz UI for flow.
  src/App.tsx
  src/apis/wallet.ts
  src/features/Aptos/Transaction/components/NonCustodial.tsx
  src/features/EVM/Transaction/components/NonCustodial.tsx
  src/features/Flow/NonCustodial/index.tsx
  src/features/Flow/PreAuthz/index.tsx
  src/features/Flow/Transaction/components/Connecting.tsx
  src/features/Flow/Transaction/components/NonCustodial.tsx
  src/features/Flow/Transaction/index.tsx
  src/features/Solana/Transaction/components/NonCustodial.tsx
  src/messages/defaultMessages.json
Labels: Feature

#54 [Feature] Add insufficient balance view.
  package.json
  src/apis/proxies/backend.ts
  src/features/Aptos/Transaction/components/Main.tsx
  src/features/Aptos/Transaction/hooks/useTransactionDetail.tsx
  src/features/EVM/Transaction/components/Connecting.tsx
  src/features/EVM/Transaction/components/Main.tsx
  src/features/EVM/Transaction/constants/index.ts
  src/features/EVM/Transaction/hooks/useTransactionDetail.tsx
  src/features/Flow/Transaction/components/Main.tsx
  src/features/Flow/Transaction/constants/index.ts
  src/features/Flow/Transaction/hooks/useTransactionDetail.ts
  src/features/Solana/Transaction/components/Main.tsx
  src/machines/transaction/definition.ts
  src/messages/defaultMessages.json
  src/utils/openMoonPayPage.ts
  yarn.lock
Labels: Feature

#57 [Fix] Manage to expose Buffer
  src/index.tsx
Labels: BugFix

#46 [Feature] Add App SDK fallback
  src/App.tsx
  src/apis/axios.ts
  src/apis/blockchain.ts
  src/apis/index.ts
  src/apis/proxies/backend.ts
  src/apis/wallet.ts
  src/features/AppSDKFallback/EVMAuthzFallback.tsx
  src/features/AppSDKFallback/EVMSignFallback.tsx
  src/features/AppSDKFallback/SolanaAuthzFallback.tsx
  src/features/AppSDKFallback/index.tsx
  src/features/Aptos/Signing/components/Connecting.tsx
  src/features/Aptos/Signing/index.tsx
  src/features/Aptos/Transaction/components/Connecting.tsx
  src/features/Aptos/Transaction/index.tsx
  src/features/Authenticate/components/Connecting.tsx
  src/features/Authenticate/index.tsx
  src/features/EVM/Signing/components/Connecting.tsx
  src/features/EVM/Signing/index.tsx
  src/features/EVM/Transaction/components/Connecting.tsx
  src/features/EVM/Transaction/index.tsx
  src/features/Flow/Signing/components/Connecting.tsx
  src/features/Flow/Signing/index.tsx
  src/features/Flow/Transaction/components/Connecting.tsx
  src/features/Flow/Transaction/index.tsx
  src/features/Solana/Transaction/components/Connecting.tsx
  src/features/Solana/Transaction/index.tsx
  src/machines/authenticate/definition.ts
  src/machines/authenticate/services.ts
  src/machines/signing/definition.ts
  src/machines/signing/services.ts
  src/machines/transaction/definition.ts
  src/machines/transaction/services.ts
  src/services/Frame/eventHandlers.ts
  src/services/LocalStorage/LocalStorage.ts
  src/utils/constants.ts
Labels: Feature

#58 [Fix] Fix the message shown on the UI for the signing message on EVM
  src/features/EVM/Signing/components/Connecting.tsx
  src/features/Flow/Signing/components/Connecting.tsx
Labels: BugFix

#59 [Fix] Getting authenticationId from the wrong place
  src/machines/authenticate/definition.ts
  src/machines/authenticate/services.ts
Labels: HotFix

#64 [Enhance] Slightly adjust cli dev-tool
  cli/dev-tool
Labels: HotFix

#65 [Fix] Set tx as verified if tx type is entry_function_payload
  src/features/Aptos/Transaction/components/Main.tsx
Labels: BugFix

#66 [Fix] Include app id in the request header
  src/apis/axios.ts
  src/machines/authenticate/services.ts
  src/services/LocalStorage/constants.ts
Labels: BugFix

#67 [Feat] Update dangerousAlert UI.
  src/components/Header/index.tsx
  src/components/Loading.tsx
  src/features/Aptos/Signing/components/NonCustodial.tsx
  src/features/Aptos/Transaction/components/NonCustodial.tsx
  src/features/Authenticate/components/Queueing.tsx
  src/features/EVM/Signing/components/NonCustodial.tsx
  src/features/EVM/Transaction/components/NonCustodial.tsx
  src/features/Flow/NonCustodial/index.tsx
  src/features/Flow/PreAuthz/index.tsx
  src/features/Flow/Transaction/components/DangerousTxAlert.tsx
  src/features/Flow/Transaction/index.tsx
  src/features/Solana/Transaction/components/NonCustodial.tsx
  src/messages/defaultMessages.json
  src/theme.ts
Labels: Feature
