Repository portto/wallet-web-ui, pull requests merged in 2023-03, with the labels that each got.

#68 [Fix] Fix transfer unit to eth with user's native token balance.
  src/features/EVM/Transaction/hooks/useTransactionDetail.tsx
Labels: BugFix

#70 Fix ui at login and tx logic bugs on evm.
  src/features/Authenticate/components/InputEmail.tsx
  src/features/EVM/Transaction/hooks/useTransactionDetail.tsx
Labels: BugFix

#71 [Feat] loading state for approve button in tx view.
  src/components/Header/index.tsx
  src/features/Aptos/Transaction/components/Main.tsx
  src/features/EVM/Transaction/components/Main.tsx
  src/features/Flow/Transaction/components/Main.tsx
  src/features/Solana/Transaction/components/Main.tsx
Labels: bug

#72 Feature/onboarding
  package.json
  src/assets/images/icons/app-store.svg
  src/assets/images/icons/google-play.svg
  src/assets/images/icons/logo-margin.svg
  src/components/DappLogo.tsx
  src/components/DownloadApp.tsx
  src/components/Field.tsx
  src/components/FieldDetail.tsx
  src/components/Header.tsx
  src/components/InnerPage.tsx
  src/components/transaction/EstimatePointErrorField.tsx
  src/components/transaction/TransactionInfo.tsx
  src/components/transaction/TransactionSent.tsx
  src/features/Aptos/Transaction/components/Main.tsx
  src/features/Aptos/Transaction/components/TxSent.tsx
  src/features/Aptos/Transaction/index.tsx
  src/features/EVM/Transaction/components/Main.tsx
  src/features/EVM/Transaction/components/TxSent.tsx
  src/features/EVM/Transaction/components/messages.js
  src/features/EVM/Transaction/index.tsx
  src/features/Flow/Transaction/components/Main.tsx
  src/features/Flow/Transaction/components/TxSent.tsx
  src/features/Flow/Transaction/index.tsx
  src/features/Solana/Transaction/components/Main.tsx
  src/features/Solana/Transaction/components/TxSent.tsx
  src/features/Solana/Transaction/index.tsx
  src/machines/transaction/definition.ts
  src/messages/defaultMessages.json
  src/theme.ts
  yarn.lock
Labels: Feature

#73 [Feat] disable approve button when estimating point.
  src/features/Aptos/Transaction/components/Main.tsx
  src/features/EVM/Transaction/components/Main.tsx
  src/features/Solana/Transaction/components/Main.tsx
Labels: BugFix

#74 Fix unit problem for user's balance on aptos and flow.
  src/features/Aptos/Transaction/hooks/useTransactionDetail.tsx
  src/features/Flow/Transaction/hooks/useTransactionDetail.ts
Labels: BugFix

#69 [Refactor] Estimate tx fee logic and ui component.
  src/apis/wallet.ts
  src/components/TransactionFeeField.tsx
  src/features/Aptos/Transaction/components/Main.tsx
  src/features/EVM/Transaction/components/Main.tsx
  src/features/Flow/Transaction/components/Main.tsx
  src/features/Solana/Transaction/components/Main.tsx
  src/hooks/useEstimatePointInterval.ts
  src/hooks/useInterval.ts
Labels: refactor

#76 [Enhance] Update translation strings for the onboarding page
  src/components/transaction/TransactionSent.tsx
  src/messages/defaultMessages.json
Labels: Feature

#81 [Fix] Should pass session id instead of auth token
  src/services/Frame/eventHandlers.ts
Labels: HotFix

#83 [Fix] Identify exceptions
  src/machines/authenticate/services.ts
Labels: HotFix

#82 Hotfix/internal wl domains condition
  src/machines/authenticate/services.ts
Labels: HotFix

#80 Feat/pay by token
  src/apis/wallet.ts
  src/assets/images/icons/point-with-mobile.svg
  src/components/DownloadApp.tsx
  src/components/Field.tsx
  src/components/FieldDetail.tsx
  src/components/InnerPage.tsx
  src/components/TransactionFeeField.tsx
  src/components/transaction/FeeOptions.tsx
  src/components/transaction/TransactionFeeField.tsx
  src/components/transaction/TransactionSent.tsx
  src/context/field.tsx
  src/features/Aptos/Transaction/components/Main.tsx
  src/features/EVM/Transaction/components/Main.tsx
  src/features/Flow/Transaction/components/Main.tsx
  src/features/Solana/Transaction/components/Main.tsx
  src/hooks/useEstimatePoint.ts
  src/machines/transaction/definition.ts
  src/messages/defaultMessages.json
  src/types.ts
Labels: Feature

#63 [Feat] add activity detail field.
  src/components/ActivityDetail.tsx
  src/components/ScrollableContainer.tsx
  src/components/transaction/TransactionFeeField.tsx
  src/features/Aptos/Transaction/components/Main.tsx
  src/features/EVM/Transaction/components/Main.tsx
  src/features/Flow/Transaction/components/Main.tsx
  src/features/Solana/Transaction/components/Main.tsx
  src/messages/defaultMessages.json
Labels: Feature

#86 [Fix] Displaying the image with a wrong way
  src/components/transaction/TransactionFeeField.tsx
Labels: HotFix

#89 [Fix] rename path
  kubernetes/dev/ingress.yaml
  kubernetes/prod/ingress.yaml
  kubernetes/staging/ingress.yaml
Labels: Feature

#88 [Feat] change endpoint for using proxy on dapps relared api.
  src/apis/proxies/backend.ts
Labels: Feature

#87 [Feat] change endpoint for using proxy on dapps relared api.
  kubernetes/dev/ingress.yaml
  kubernetes/prod/ingress.yaml
  kubernetes/staging/ingress.yaml
  src/apis/proxies/backend.ts
Labels: Feature

#90 Feature/aptos fallback
  src/App.tsx
  src/features/AppSDKFallback/index.tsx
  src/features/Aptos/Transaction/components/Connecting.tsx
  src/machines/authenticate/services.ts
  src/types.ts
Labels: Feature

#93 [Refactor] Get the requestId from the response
  src/apis/wallet.ts
  src/features/Aptos/Transaction/components/Connecting.tsx
  src/types.ts
Labels: Feature

#18 Add script for download intl strings.
  .babelrc
  exchangePathname.zip
  package.json
  src/scripts/helpers.js
  src/scripts/i18n.js
  src/scripts/intl.js
  src/translations/en.json
  src/translations/ja.json
  src/translations/ko.json
  src/translations/ru.json
  src/translations/zh-Hans.json
  src/translations/zh-Hant.json
  yarn.lock
Labels: Feature

#91 Fix: disable approve button when user has insufficient point.
  src/components/transaction/FeeOptions.tsx
  src/components/transaction/TransactionFeeField.tsx
  src/features/Aptos/Transaction/components/Connecting.tsx
  src/features/Aptos/Transaction/components/Main.tsx
  src/features/Aptos/Transaction/index.tsx
  src/features/EVM/Transaction/components/Connecting.tsx
  src/features/EVM/Transaction/components/Main.tsx
  src/features/EVM/Transaction/index.tsx
  src/features/Flow/Transaction/components/Connecting.tsx
  src/features/Flow/Transaction/index.tsx
  src/features/Solana/Transaction/components/Connecting.tsx
  src/features/Solana/Transaction/components/Main.tsx
  src/features/Solana/Transaction/index.tsx
  src/types.ts
Labels: Feature, BugFix
